name: Run tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    name: OTP ${{ matrix.otp-version }}
    strategy:
      fail-fast: false
      matrix:
        otp-version: ['27.3.4.15', '28.0']
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          rebar3-version: '3.27.0'

      - name: Build compatible Clojerl
        run: |
          git clone --branch 0.9.1 --depth 1 https://github.com/antlobach/clojerl.git ../clojerl
          make -C ../clojerl compile

      - name: Run Chassis tests
        run: make test

      - name: Test Cowboy example
        working-directory: examples/cowboy
        run: rebar3 clojerl test
